target-version = "py310"
line-length = 120

exclude = [".venv/"]

lint.select = ["I", "F", "E", "W", "UP", "SIM", "N"]
lint.ignore = ["N818", "SIM114", "SIM117"]  # N818: exception naming, SIM114: combined ifs, SIM117: nested with
